# Fly.io конфигурация для Telegram бота
app = "telegram-bot-top-padla"
primary_region = "fra"

[build]

[env]
  BOT_TOKEN = ""
  WEB_API_URL = "https://qwerty123.eu"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[processes]]
  name = "app"
  command = "python main.py"
  cpu_shares = 100
  memory_mb = 256

